name: acquirer
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#------------------Packages------------------
dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  lottie: ^3.1.0
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.1
  cached_network_image_web: ^1.2.0
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  file_picker: ^8.0.3

  #Icons
  cupertino_icons: ^1.0.6

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Product Specific
  flutter_rating_bar: ^4.0.1

  #FireBase
  firebase_core: ^2.30.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4

#------------------Packages End------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #------------------Local Assets------------------
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/brands/
    - assets/images/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/animations/141594-animation-of-docer.json

  #------------------Local Fonts------------------
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
